#!/usr/bin/env python3
"""Deep-merge a delta overlay onto a base omp config.yml.

Mirrors PI_CONFIG_FILES overlay semantics: dicts merge key-by-key,
recursively; any other type (including lists) is replaced wholesale by
the overlay's value - config-devcontainer.yml documents this same
contract for its own bash.patterns list.

Used by install.sh to bake config-devcontainer.yml into config.yml at
install time on devcontainer hosts. Needed because captain-miao's
remote/pooled session spawn (miao-server launches the agent binary
directly with a hardcoded minimal env) never runs a shell, so a
PI_CONFIG_FILES env var set in .profile/.zshenv never reaches the
process - the overlay has to already be baked into the file omp loads
by default.

Usage: merge-config.py <base.yml> <overlay.yml> <output.yml>
"""
import sys

import yaml


def deep_merge(base, overlay):
    if isinstance(base, dict) and isinstance(overlay, dict):
        merged = dict(base)
        for key, value in overlay.items():
            merged[key] = deep_merge(merged[key], value) if key in merged else value
        return merged
    return overlay


def main():
    if len(sys.argv) != 4:
        sys.exit(f"usage: {sys.argv[0]} <base.yml> <overlay.yml> <output.yml>")
    base_path, overlay_path, out_path = sys.argv[1:4]

    with open(base_path) as f:
        base = yaml.safe_load(f) or {}
    with open(overlay_path) as f:
        overlay = yaml.safe_load(f) or {}

    merged = deep_merge(base, overlay)

    with open(out_path, "w") as f:
        f.write(
            "# Generated by install.sh: config.yml deep-merged with config-devcontainer.yml\n"
            "# (see .omp/merge-config.py). Do not edit directly - edit the source files in\n"
            "# the dotfiles repo and re-run install.sh.\n"
        )
        yaml.safe_dump(merged, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


if __name__ == "__main__":
    main()
